all:
	make -B -C ../generator
	make -B -C ../serial
	make -B -C ../mpi/ptp/continuous-single 
	make -B -C ../mpi/ptp/hybrid 
	make -B -C ../mpi/collective/hybrid
	make -B -C ../mpi/collective/continuous-single
	make -B -C ../openmp



